version: 2
updates:
  - package-ecosystem: "poetry" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "james-ecd"
